test:
	mvn clean test -DENV=${ENV} -DGIT_BRANCH=${BRANCH} -DBUILD_NUMBER=${BUILD_NUMBER} -DGIT_COMMIT=${GIT_COMMIT} -DCOMPONENT_ID=$(COMPONENT_ID) -DSendEmailAfterExecution=$(SEND_EMAIL) -DREPOSITORY_NAME=$(REPOSITORY_NAME)

dev:
	mvn clean test -DENV=${ENV} -DGIT_BRANCH=${BRANCH} -DBUILD_NUMBER=${BUILD_NUMBER} -DGIT_COMMIT=${GIT_COMMIT} -DCOMPONENT_ID=$(COMPONENT_ID) -DSendEmailAfterExecution=$(SEND_EMAIL) -DREPOSITORY_NAME=$(REPOSITORY_NAME)




